Repository openconfig/public, pull requests merged in 2022-05, with the labels that each got.

#439 Add initial support for L2VPN EVPN extensions for BGP RIB
  release/models/network-instance/openconfig-evpn-types.yang
  release/models/rib/openconfig-rib-bgp-tables.yang
  release/models/rib/openconfig-rib-bgp.yang
Labels: cla: yes, shepherd-assigned

#437 Add initial support for EVPN VXLAN Overlay Endpoint Oper Data
  release/models/network-instance/openconfig-evpn.yang
Labels: cla: yes, shepherd-assigned

#527 Add initial support for L2RIB EVPN state extensions
  release/models/network-instance/openconfig-network-instance-l2.yang
  release/models/network-instance/openconfig-network-instance.yang
Labels: cla: yes, shepherd-assigned, awaiting-upstream-pr

#513 adds extended next-hop encoding config/state for BGP
  release/models/bgp/openconfig-bgp-common-multiprotocol.yang
  release/models/bgp/openconfig-bgp-common-structure.yang
  release/models/bgp/openconfig-bgp-common.yang
  release/models/bgp/openconfig-bgp-global.yang
  release/models/bgp/openconfig-bgp-neighbor.yang
  release/models/bgp/openconfig-bgp-peer-group.yang
  release/models/bgp/openconfig-bgp.yang
Labels: cla: yes, shepherd-assigned

#534 Update remainder of regex pattern statements for XSD conformance
  regexp-tests/openconfig-openflow-types-test.yang
  regexp-tests/openconfig-vlan-types-test.yang
  release/models/bgp/openconfig-bgp-policy.yang
  release/models/openflow/openconfig-openflow-types.yang
  release/models/policy/openconfig-routing-policy.yang
  release/models/vlan/openconfig-vlan-types.yang
  release/models/wifi/openconfig-ap-manager.yang
Labels: cla: yes
