Repository openconfig/public, pull requests merged in 2023-02, with the labels that each got.

#754 Hardware Resource Thresholds
  release/models/platform/openconfig-platform-common.yang
  release/models/platform/openconfig-platform.yang
Labels: non-breaking

#774 Remove the default of "enabled" of BGP AFI-SAFI to support BGP inheritance model
  release/models/bgp/openconfig-bgp-common-multiprotocol.yang
  release/models/bgp/openconfig-bgp-common-structure.yang
  release/models/bgp/openconfig-bgp-common.yang
  release/models/bgp/openconfig-bgp-global.yang
  release/models/bgp/openconfig-bgp-neighbor.yang
  release/models/bgp/openconfig-bgp-peer-group.yang
  release/models/bgp/openconfig-bgp.yang
Labels: non-breaking, last-call

#762 Control plane access control list and QoS
  release/models/acl/openconfig-acl.yang
  release/models/qos/openconfig-qos-elements.yang
  release/models/qos/openconfig-qos-interfaces.yang
  release/models/qos/openconfig-qos-mem-mgmt.yang
  release/models/qos/openconfig-qos.yang
  release/models/system/.spec.yml
  release/models/system/openconfig-system-controlplane.yang
Labels: non-breaking, last-call

#763 Vendor-specific control-plane traffic counters
  doc/vendor_counter_guide.md
  release/models/platform/openconfig-platform-pipeline-counters.yang
Labels: non-breaking, last-call

#791 Add a clarification and examples for port breakout mode.
  release/models/platform/openconfig-platform-port.yang
Labels: non-breaking, last-call

#756 Remove incorrect QoS output interface-ref
  release/models/qos/openconfig-qos-elements.yang
  release/models/qos/openconfig-qos-interfaces.yang
  release/models/qos/openconfig-qos-mem-mgmt.yang
  release/models/qos/openconfig-qos.yang
Labels: non-breaking, last-call

#807 Patch 1
  release/models/platform/openconfig-platform-port.yang
  release/models/policy-forwarding/openconfig-pf-interfaces.yang
Labels: non-breaking

#810 Fix lint issues in openconfig-platform-transceiver
  release/models/platform/openconfig-platform-transceiver.yang
Labels: non-breaking

#808 openconfig-transport-types.yang add ETH_100GBASE_DR PMD type
  release/models/optical-transport/openconfig-transport-types.yang
Labels: non-breaking, last-call

#796 Add support for AND/OR for flags; built-in flag match criteria.
  release/models/acl/openconfig-packet-match.yang
Labels: breaking, last-call

#731 modify /interfaces/interface/loopback-mode to allow specification of loopback-mode-type
  release/models/interfaces/openconfig-interfaces.yang
Labels: breaking, last-call

#777 add isis max-ecmp-paths for address family
  release/models/isis/openconfig-isis-lsp.yang
  release/models/isis/openconfig-isis-routing.yang
  release/models/isis/openconfig-isis.yang
Labels: non-breaking, last-call

#804 network-instance - add prefixes to identity values in when statements
  release/models/network-instance/openconfig-network-instance-l2.yang
  release/models/network-instance/openconfig-network-instance.yang
Labels: non-breaking

#772 Add support for defining a queue identifier under queues.
  release/models/qos/openconfig-qos-elements.yang
  release/models/qos/openconfig-qos-interfaces.yang
  release/models/qos/openconfig-qos-mem-mgmt.yang
  release/models/qos/openconfig-qos.yang
Labels: non-breaking, last-call

#793 Add ipv6 link local address configuration
  release/models/interfaces/openconfig-if-ip.yang
  release/models/types/openconfig-inet-types.yang
Labels: non-breaking, last-call

#800 vlan - remove prefixes from enum values in condition clauses
  release/models/vlan/openconfig-vlan.yang
Labels: non-breaking, last-call
