Repository openconfig/public, pull requests merged in 2024-07, with the labels that each got.

#1144 Add 25G SR/LR PMDs to openconfig-transport-types.
  release/models/optical-transport/openconfig-transport-types.yang
Labels: non-breaking

#911 Terminal-device-properties-v2 initial commit
  doc/terminal-device-properties-guide.md
  release/models/devices-manifest/openconfig-terminal-device-properties.yang
  release/models/devices-manifest/openconfig-terminal-device-property-types.yang
Labels: non-breaking

#1084 Add `ext-community-count` container and clarify that `community-count` does not include extended communities.
  release/models/bgp/openconfig-bgp-policy.yang
Labels: non-breaking

#930 Add vpws local and remote identifiers to EVPN-VPWS configuration
  release/models/network-instance/openconfig-evpn.yang
Labels: non-breaking, last-call

#1151 Remove unused top-level 'messages' container
  release/models/system/openconfig-messages.yang
Labels: non-breaking

#895 Add transition OPMODES to wifi-phy models
  release/models/wifi/openconfig-wifi-phy.yang
Labels: non-breaking

#454 Add regression tests for bugs in route-distinguisher regex
  regexp-tests/openconfig-network-instance-types-test.yang
Labels: cla: yes, non-breaking, Stale

#1014 add hex-string-prefixed typedef
  regexp-tests/openconfig-yang-types-test.yang
  release/models/keychain/openconfig-keychain.yang
  release/models/policy/openconfig-policy-types.yang
  release/models/types/openconfig-yang-types.yang
Labels: non-breaking

#1130 Optical channel reference to it's logical channel
  release/models/optical-transport/openconfig-terminal-device.yang
Labels: non-breaking
