Repository openconfig/public, pull requests merged in 2024-10, with the labels that each got.

#1153 Add aft encapsulation-headers
  release/models/aft/openconfig-aft-common.yang
  release/models/aft/openconfig-aft-ethernet.yang
  release/models/aft/openconfig-aft-ipv4.yang
  release/models/aft/openconfig-aft-ipv6.yang
  release/models/aft/openconfig-aft-mpls.yang
  release/models/aft/openconfig-aft-pf.yang
  release/models/aft/openconfig-aft-state-synced.yang
  release/models/aft/openconfig-aft-types.yang
  release/models/aft/openconfig-aft.yang
Labels: non-breaking, last-call

#1119 Added PIM bidirectional mode to the PIM_MODE type (#1118).
  release/models/multicast/openconfig-pim-types.yang
Labels: non-breaking

#1189 Define how physical channel power leaves are used.
  release/models/platform/openconfig-platform-transceiver.yang
Labels: non-breaking, last-call

#1109 Updates to the ES model to allow the configuration of an ES-import route target
  release/models/ethernet-segments/openconfig-ethernet-segments.yang
Labels: non-breaking, last-call

#1165 Refactor non-compliant/overlapping YANG definition for BGP MED
  release/models/bgp/openconfig-bgp-policy.yang
Labels: breaking, last-call

#1195 Update openconfig-gnsi-acctz.yang
  release/models/gnsi/openconfig-gnsi-acctz.yang
Labels: non-breaking, last-call

#1185 Correct typo in protocol-name description
  release/models/network-instance/openconfig-network-instance-policy.yang
Labels: non-breaking

#1183 Refactor physical ethernet vs. aggregate interface characteristics
  release/models/interfaces/openconfig-if-ethernet.yang
Labels: non-breaking, last-call
